app:
  name: "Device Communication"
  version: ${COM_APP_VERSION:"v1"}
vertx:
  openapi:
    file: ${COM_OPENAPI_FILE_PATH:api/hono-device-communication-v1.yaml}

  server:
    url: ${COM_SERVER_HOST:0.0.0.0}
    port: ${COM_SERVER_PORT:8080}
    paths:
      base: ${COM_SERVER_BASE_PATH:/api/v1/}  # base path should always end with "/"
      liveness: ${COM_SERVER_LIVENESS_PATH:/alive}
      readiness: ${COM_SERVER_READINESS_PATH:/ready}

  database:
    pool-max-size: ${COM_POOL_MAX_SIZE:5}
    name: ${COM_DB_NAME:hono}
    host: ${COM_DB_HOST:localhost}
    port: ${COM_DB_PORT:5432}
    username: ${COM_DB_USERNAME:postgres}
    password: ${COM_DB_PASSWORD:mysecretpassword}
    db-kind: "postgresql"

  # Device registration table configs. Used for validating devices
  device-registration:
    table: ${COM_DB_DEVICE_REG_TABLE:device_registrations}
    tenant-id-column: ${COM_DB_DEVICE_REG_TENANT_COL_NAME:tenant_id}
    device-id-column: ${COM_DB_DEVICE_REG_DEVICE_COL_NAME:device_id}

quarkus:
  container-image:
    builder: docker
    build: false
    push: false
    image: "eclipse/hono-device-communication"
