app:
  name: "Device Communication"
  version: ${COM_APP_VERSION:"v1"}
  projectId: ${COM_PROJECT_ID:sotec-iot-core-dev}

  internalMessaging:
    message:
      attributeKeys:
        deviceIdKey: ${COM_EVENT_ATTRIBUTE_DEVICE_ID:deviceId}
        tenantIdKey: ${COM_EVENT_ATTRIBUTE_TENANT_ID:tenantId}
        configVersionIdKey: ${COM_EVENT_ATTRIBUTE_CONFIG_VERSION:config-version}
        contentTypeKey: ${COM_EVENT_ATTRIBUTE_CONTENT_TYPE:content-type}
    event:
      topicFormat: ${COM_EVENT_ON_CONNECT_TOPIC_FORMAT:%s.event} # TENANT_NAME.event
      emptyNotificationEventContentType: ${COM_EVENT_EMPTY_NOTIFICATION_CONTENT_TYPE:application/vnd.eclipse-hono-empty-notification}

    state:
      topicFormat: ${COM_STATE_TOPIC_FORMAT:%s.event.state}  # TENANT_NAME.event.state
    config:
      ackTopic: ${COM_CONFIG_ACK_TOPIC:%s.config_response} # TENANT_NAME.config_response
      topicFormat: ${COM_CONFIG_TOPIC_FORMAT:%s.config}  # TENANT_NAME.config
    command:
      topicFormat: ${COM_COMMAND_TOPIC_FORMAT:%s.command} # TENANT_NAME.command

vertx:
  openapi:
    file: ${COM_OPENAPI_FILE_PATH:api/hono-device-communication-v1.yaml}

  server:
    url: ${COM_SERVER_HOST:0.0.0.0}
    port: ${COM_SERVER_PORT:8080}
    paths:
      base: ${COM_SERVER_BASE_PATH:/v1/}  # base path should always end with "/"
      liveness: ${COM_SERVER_LIVENESS_PATH:/alive}
      readiness: ${COM_SERVER_READINESS_PATH:/ready}

  database:
    pool-max-size: ${COM_POOL_MAX_SIZE:5}
    name: ${COM_DB_NAME:hono}
    host: ${COM_DB_HOST:host.docker.internal}
    port: ${COM_DB_PORT:5432}
    username: ${COM_DB_USERNAME:postgres}
    password: ${COM_DB_PASSWORD:mysecretpassword}
    db-kind: "postgresql"

  # Tenant table configs. Used for listing tenants
  tenant:
    table: ${COM_DB_TENANT_TABLE:tenants}
    tenant-id-column: ${COM_DB_TENANT_COL_NAME:tenant_id}

  # Device registration table configs. Used for validating devices
  device-registration:
    table: ${COM_DB_DEVICE_REG_TABLE:device_registrations}
    tenant-id-column: ${COM_DB_DEVICE_REG_TENANT_COL_NAME:tenant_id}
    device-id-column: ${COM_DB_DEVICE_REG_DEVICE_COL_NAME:device_id}


quarkus:
  container-image:
    builder: docker
    build: true
    push: false
    image: "gcr.io/sotec-iot-core-dev/hono-device-communication:sandbox-release-2-4-0"