# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

# This workflow will build the included maven modules.

name: Build

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build MQTT Protocol Gateway Template
        working-directory: ./protocol-gateway/mqtt-protocol-gateway-template
        run: mvn install -B -e -DcreateJavadoc=true
      - name: Build Azure IoT Protocol Gateway Example
        working-directory: ./protocol-gateway/azure-mqtt-protocol-gateway
        run: mvn install -B -e -DcreateJavadoc=true
